name: desole_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.3.0
  intl: ^0.19.0
  url_launcher: ^6.2.4
  dio: ^5.4.0
  table_calendar: ^3.0.7
  dotted_border: ^2.0.0
  image_picker: ^1.1.0
  permission_handler: ^11.0.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img_logo.png"

flutter_native_splash:
  color: "#ffffff" 
  image: assets/img_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/img_logo.png
